[package]
name = "imputio-utils"
version = "0.2.2"
edition = "2024"

[dependencies]
futures-lite.workspace=true
flume= {workspace=true, features=["async"]}
tracing.workspace=true
thiserror.workspace=true
imputio.workspace=true

[features]
delay-delete=[]